### ISSUE TITLE
Text input bar moving too far up when vc is contained

### ISSUE THREAD

**Issue by clayellis** [smooch/smooch-ios#123]
Instead of using `Smooch.show()` I'm setting `Smooch.newConversationViewController()` as a child controller to my parent like so:

```swift
// In a UIViewController subclass which is pushed onto a UINavigationController
if let smoochViewController = Smooch.newConversationViewController() {
    addChildViewController(smoochViewController)
    smoochViewController.didMove(toParentViewController: self)
    view.addSubview(smoochViewController.view)
    smoochViewController.view.translatesAutoresizingMaskIntoConstraints = false
    NSLayoutConstraint.activate([
        smoochViewController.view.leftAnchor.constraint(equalTo: view.leftAnchor),
        smoochViewController.view.rightAnchor.constraint(equalTo: view.rightAnchor),
        smoochViewController.view.topAnchor.constraint(equalTo: view.topAnchor),
        smoochViewController.view.bottomAnchor.constraint(equalTo: view.bottomAnchor)
        ])
}
```
Which gives me this:

![fullsizeoutput_18ec](https://cloud.githubusercontent.com/assets/10712068/22123349/88930322-de48-11e6-96a4-8ae0746dc491.jpeg)

Looks good. However, when I tap the "Type a message..." text field and the keyboard shows I get this...

![fullsizeoutput_18f4](https://cloud.githubusercontent.com/assets/10712068/22123396/af35de32-de48-11e6-8e39-1c5ab28c3843.jpeg)

The bar is `44pts` above the keyboard which makes me think it's trying to compensate for a `UITabBar` being at the bottom... or something fishy like that... 

Has anyone seen this before? Anyone have any ideas on how to fix this? I really like using `newConversationViewController()` over `show()` to make it feel more a part of the app.

**Comment by mspensieri** [comment]
We've seen variations of this bug before, yes. Most recently in https://github.com/smooch/smooch-ios/issues/113, which was supposed to have been fixed in v5.4.0.

Which version are you on?
Do you think you could craft a sample project reproducing the issue?

**Comment by clayellis** [comment]
@mspensieri I'm on `5.4.2`. Sure I'll try to get one up by the end of the day. I'm liking Smooch, by the way. You guys are giving us a serious boost when we needed it.

**Comment by marbetschar** [comment]
Same issue here. Just updated to `5.4.5`, but still encountering this issue - as soon as the `UITextField` is getting activated.

**Before activation of the `UITextField`**

![simulator screen shot 04 02 2017 14 57 06](https://cloud.githubusercontent.com/assets/392542/22618972/8350e75e-eaea-11e6-8710-c322f2b3bc82.png)

**After activation of the `UITextField`**

![simulator screen shot 04 02 2017 14 57 11](https://cloud.githubusercontent.com/assets/392542/22618974/8901f47c-eaea-11e6-8c71-438b397befcb.png)

**Comment by marbetschar** [comment]
@mspensieri as promised I've put together a demo project which is showcasing the placement issue I'm encountering:  [SmoochPlacementIssueDemo.zip](https://github.com/smooch/smooch-ios/files/763679/SmoochPlacementIssueDemo.zip)


After you've unpacked the zip file, make sure to run `carthage bootstrap` and insert a valid app token in the AppDelegate.

**Comment by marbetschar** [comment]
FWIW: You might want to look at the following code in `FolderBar/MNKFolderBarController`. The following code of it is responsible for swapping the currently visible controller. I suspect there's something which causes Smooch to make wrong assumptions?

```
open var selectedViewController: UIViewController?{
		willSet{
			guard let oldValue = self.selectedViewController else{
				return
			}
			guard newValue != oldValue else{
				let navigationController: UINavigationController? = {
					if let controller = newValue as? UINavigationController{
						return controller
					} else if let controller = newValue?.navigationController{
						return controller
					}
					return nil
					}()
				let _ = navigationController?.popToRootViewController(animated: true)
				return
			}
			
			if let selectedIndexPath = self.selectedIndexPath{
				self.collectionView?.deselectItem(at: selectedIndexPath, animated: true)
			}
			
			oldValue.willMove(toParentViewController: nil)
			oldValue.view.removeFromSuperview()
			oldValue.removeFromParentViewController()
		}
		didSet{
			guard let newValue = self.selectedViewController, newValue != oldValue else{
				return
			}
			
			self.addChildViewController(newValue)
			if let contentView = self.contentView{
				contentView.addSubview(newValue.view)
			
				newValue.view.frame = contentView.bounds
				newValue.view.autoresizingMask = [.flexibleWidth,.flexibleHeight]
			}
			newValue.didMove(toParentViewController: self)
			
			if let selectedIndexPath = self.selectedIndexPath{
				self.collectionView?.selectItem(at: selectedIndexPath, animated: true,scrollPosition: UICollectionViewScrollPosition())
			}
		}
	}
```

**Comment by janweinkauff** [comment]
Same for me with v5.4.5. 

`Smooch.newConversationViewController()` is added as root view controller of an `UINavigationController`.

Between toolbar (`SKTSOMessageInputView`) and keyboard arises a small space.

<img width="376" alt="bildschirmfoto 2017-02-13 um 13 06 21" src="https://cloud.githubusercontent.com/assets/142565/22882822/4cee8e82-f1ed-11e6-8c57-2ba0b523deff.png">

**Comment by danilobuerger** [comment]
+1

**Comment by wmora** [comment]
thanks for the sample project reproducing the issue @marbetschar, we're working on a fix

**Comment by wmora** [comment]
We just released [v5.5.0](https://github.com/smooch/smooch-ios/releases/tag/5.5.0) with the fix, let us know if you're still having issues with the input placement

**Comment by marbetschar** [comment]
Works like a charm - thank you!!!
