### ISSUE TITLE
unread doesn't work

### ISSUE THREAD

**Issue by rvi** [smooch/smooch-ios#148]
I'm  on the version `5.6.1` of your SDK, and when the user open the chat (the number of unread become 0), but when we kill the app and re-open it, the number of unread message is 1...

Same behavior with `markAllAsRead()`, it doesn't work...

Can you fix it asap please?

**Comment by wmora** [comment]
Hi @rvi thanks for reporting. Unfortunately we're not able to reproduce the issue as described. Would it be possible to share a video reproducing the bug? Thanks in advance

**Comment by rvi** [comment]
Thanks @wmora,
Here is the bug in, the video: https://drive.google.com/file/d/0B0g6CU9FMYUWZXl5QmJJQXF3Mk0/view?usp=sharing


How to reproduce:

1. Open the app, create a cell by tapping on the '+' button (this is just the sample iOS app, we don't care of this part)
1. Start the chat, say hello
1. Close the chat
1. On another app integrated with Smooch (Slack for example), reply to this user
1. Go back on the iPhone, now the unread count is 1, which is normal.
1. Open the chat, see the reply but don't reply something else, the unread count is 0, normal.
1. Kill the app
1. Reopen it, and now you can see **the unread count is back 1**, without new messages!

Code to reproduce: https://github.com/rvi/Smooch-bug/

**Comment by wmora** [comment]
yes, actually we just released version [5.6.2](https://github.com/smooch/smooch-ios/releases/tag/5.6.2) with the fix

Thanks a lot for the video reproducing the issue, it was very helpful

**Comment by rvi** [comment]
I still have the bug on my app, with the version 5.6.2 of your SDK...

**Comment by abadikaka** [comment]
@wmora  yeah me too.. the same thing after upgrade to 5.6.2, if we dont reply it, it still goes to 1.

**Comment by wmora** [comment]
🤔 it works for me, here's a couple of gifs reproducing the issue with the same code you provided, one with 5.6.1 and the other one with 5.6.2. If there's something I missed let me know

## 5.6.1
![5 6 1](https://cloud.githubusercontent.com/assets/2448046/24967943/a6183f8a-1f79-11e7-8f7c-a28bfbf320ab.gif)

## 5.6.2
![5 6 2](https://cloud.githubusercontent.com/assets/2448046/24967947/aa35b2c8-1f79-11e7-8d05-74628cb571cc.gif)

**Comment by rvi** [comment]
It's weird. With the sample code I wrote, it's fixed, but not in my app.. I can record another video

**Comment by rvi** [comment]
I reproduced it on the sample code I provide you (and updated the code on github), and here is a video: https://drive.google.com/file/d/0B0g6CU9FMYUWVjZ5NTEyWXZpUjA/view?usp=sharing

**Comment by wmora** [comment]
ok, thanks again for the video! I'll take a look at it as soon as I get a chance

**Comment by rvi** [comment]
Thanks. You can reproduce it with this code: https://github.com/rvi/Smooch-bug/

**Comment by wmora** [comment]
Should be fixed with the latest version [5.6.4](https://github.com/smooch/smooch-ios/releases/tag/5.6.4)

![unread_bug](https://cloud.githubusercontent.com/assets/2448046/25016059/84ee5776-204c-11e7-8e37-95ece0c096ea.gif)

**Comment by rvi** [comment]
Thanks!
